wanted/urls.py
from django.urls import include, path

from . import views

app_name = 'wanted'
urlpatterns = [
    path('', views.company_list, name = 'company'),
    path('<int:company_id>/',views.company_detail, name='detail'),
    path('create/', views.company_create, name='create'),
    path('edit/<int:company_id>/',views.company_edit, name='edit'),
    path('delete/<int:company_id>',views.company_delete, name='delete')
]

wanted_api/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from rest_framework import routers
# from wanted.views import CompanyViewSet

# routers = routers.DefaultRouter()
# routers.register('wanted',CompanyViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wanted/', include('wanted.urls')),
]

wanted/models.py
from django.db import models

# Create your models here.
class Company(models.Model):
    position = models.CharField(max_length=200)
    money = models.IntegerField(default=0)
    detail = models.CharField(max_length=200)
    skill = models.CharField(max_length=200)

    def __str__(self):return self.position

wanted/forms.py
from django import forms
from wanted.models import Company

class CompanyCreateForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['position','money','detail','skill']

wanted/views.py
from django.shortcuts import get_object_or_404, render, redirect

# Create your views here.

from rest_framework import viewsets
from .serializers import CompanySerializer
from .models import Company
from .forms import CompanyCreateForm

# class CompanyViewSet(viewsets.ModelViewSet):
#     queryset = Company.objects.all()
#     serializer_class = CompanySerializer

def company_create(request):
    """
    채용공고 등록
    """
    if request.method == 'POST':
        form = CompanyCreateForm(request.POST)
        if form.is_valid():
            company = form.save(commit=False)
            company.save()
            return redirect('wanted:company')
    else:
        form = CompanyCreateForm()
    context = {'form':form}
    return render(request, 'company/company_form.html',context)

def company_list(request):
    """
    채용공고 출력
    """
    company_list = Company.objects.all()
    context = {'company_list':company_list}
    return render(request, 'company/company_list.html',context)

def company_delete(request,company_id):
    """
    채용공고 삭제
    """
    company = Company.objects.get(id=company_id)
    company.delete()
    return redirect('wanted:company')

def company_edit(request,company_id):
    """
    채용공고 수정
    """
    company = get_object_or_404(Company, pk=company_id)
    if request.method == "POST":
        form = CompanyCreateForm(request.POST, instance=company)
        if form.is_valid():
            company=form.save(commit=False)
            company.save()
            return redirect('wanted:detail', company_id=company.id)
    else:
        form = CompanyCreateForm(instance=company)
    context = {'form':form}
    return render(request, 'company/company_form.html',context)

def company_detail(request, company_id):
    """
    채용공고 내용 출력
    """
    company = Company.objects.get(id=company_id)
    context = {'company':company}
    return render(request, 'company/company_detail.html',context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
<!--    Required meta tags-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!--    Bootstrap CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css'%}">
<!--    taeri CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!--기본 템플릿 안에 삽입될 내용 start-->
{% block content %}
{% endblock %}
<!--기본 템플릿 안에 삽입될 내용 end-->
</body>
</html>

templates/company/company_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
<form action="{% url 'wanted:create' company.id %}" method="post">
    {% csrf_token %}
    <h4>채용포지션</h4><textarea name="position" id = "position"></textarea>
    <h4>채용보상금</h4><textarea name="money" id = "money"></textarea>
    <h4>채용내용</h4><textarea name="detail" id = "detail"></textarea>
    <h4>사용기술</h4><textarea name="skill" id = "skill"></textarea>

    <input type="submit" value="채용공고 등록">
</form>
</html>

templates/company/company_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table class="table">
    <h3>회사id : {{ company.id }}</h3>
    <h3>채용포지션 : {{ company.position }}</h3>
    <h3>채용보상금 : {{ company.money }}</h3>
    <h3>채용 내용 : {{ company.detail }}</h3>
    <h3>사용기술 : {{ company.skill }}</h3>
</table>
<div class="my-3">
    <a href="{% url 'wanted:edit' company.id %}" class="btn btn-sm btn-outline-secondary">수정하기</a>
    <a href="{% url 'wanted:delete' company.id %}" class="btn btn-sm btn-outline-secondary">삭제하기</a>
</div>

</body>

</html>

templates/company/company_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
<form action="{% url 'wanted:edit' company.id %}" method="post">
    {% csrf_token %}
    <h4>채용포지션</h4><textarea name="position" id = "position"></textarea>
    <h4>채용보상금</h4><textarea name="money" id = "money"></textarea>
    <h4>채용내용</h4><textarea name="detail" id = "detail"></textarea>
    <h4>사용기술</h4><textarea name="skill" id = "skill"></textarea>

    <input type="submit" value="채용공고 수정">
</form>
</html>

templates/company/company_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">회사 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/company/company_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>포지션</th>
            <th>채용보상금</th>
        </tr>
        </thead>
        <tbody>
        {% if company_list %}
        {% for company in company_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'wanted:detail' company.id %}">
                    {{ company.position }}
                </a>
            </td>
            <td>{{ company.money }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">채용 공고가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'wanted:create' %}" class="btn btn-primary">
        채용공고 등록하기
    </a>
</div>
{% endblock %}